#!/bin/bash --login
#
#SBATCH --account=pawsey0106
#SBATCH --time=01:00:00
#SBATCH --export=NONE
#SBATCH --partition=work
#SBATCH --output=LOGS/pythonjob-%j.out
##SBATCH --mail-type=ALL
##SBATCH --mail-user=matt.rayson@uwa.edu.au
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8

########################################################################
#
# Shell script to run a suntans test case.
#
########################################################################

# Containerised python environment
module load ffmpeg/4.4
module load singularity/3.8.6

containerDir=/software/projects/pawsey0106/singularity
export containerImage=$containerDir/jupyter_sfoda_20220831.sif
PYTHONEXEC="singularity exec $containerImage python -u"

makescript=$1

$PYTHONEXEC $makescript "$2" "$3" "$4" "$5"
